import { Component, OnInit } from '@angular/core';

@Component({
  selector: 'app-user-table',
  templateUrl: './user-table.component.html',
  styleUrls: ['./user-table.component.css']
})
export class UserTableComponent implements OnInit {

  users = [
    {id: 1,
    name: 'Supriya Kadakia',
    username: 'supriyakadakia',
    email: 'janesmith@example.com',
    address: '90, Urmila Nagar, Ahmedabad - 119891',
    phone: '+91 886 4414692',
    company: 'Widgets Ltd'},
    {id: 2,
      name: 'Jane Smith',
      username: 'janesmith',
      email: 'janesmith@example.com',
      address: '456 Oak St, Anytown USA',
      phone: '555-987-6543',
      company: 'Widgets Ltd'},
    {id: 3,
        name: 'Supriya Kadakia',
        username: 'supriyakadakia',
        email: 'janesmith@example.com',
        address: '90, Urmila Nagar, Ahmedabad - 119891',
        phone: '+91 886 4414692',
        company: 'Widgets Ltd'},
    {id: 4,
          name: 'Supriya Kadakia',
          username: 'supriyakadakia',
          email: 'janesmith@example.com',
          address: '90, Urmila Nagar, Ahmedabad - 119891',
          phone: '+91 886 4414692',
          company: 'Widgets Ltd'},    
    {id: 5,
            name: 'Supriya Kadakia',
            username: 'supriyakadakia',
            email: 'janesmith@example.com',
            address: '90, Urmila Nagar, Ahmedabad - 119891',
            phone: '+91 886 4414692',
            company: 'Widgets Ltd'},
    {id: 6,
     name: 'Supriya Kadakia',
              username: 'supriyakadakia',
              email: 'janesmith@example.com',
              address: '90, Urmila Nagar, Ahmedabad - 119891',
              phone: '+91 886 4414692',
              company: 'Widgets Ltd'},
              {id: 7,
                name: 'Supriya Kadakia',
                username: 'supriyakadakia',
                email: 'janesmith@example.com',
                address: '90, Urmila Nagar, Ahmedabad - 119891',
                phone: '+91 886 4414692',
                company: 'Widgets Ltd'},
                {id: 8,
                  name: 'Supriya Kadakia',
                  username: 'supriyakadakia',
                  email: 'janesmith@example.com',
                  address: '90, Urmila Nagar, Ahmedabad - 119891',
                  phone: '+91 886 4414692',
                  company: 'Widgets Ltd'},
                  {id: 9,
                    name: 'Supriya Kadakia',
                    username: 'supriyakadakia',
                    email: 'janesmith@example.com',
                    address: '90, Urmila Nagar, Ahmedabad - 119891',
                    phone: '+91 886 4414692',
                    company: 'Widgets Ltd'},
                    {id: 10,
                      name: 'Supriya Kadakia',
                      username: 'supriyakadakia',
                      email: 'janesmith@example.com',
                      address: '90, Urmila Nagar, Ahmedabad - 119891',
                      phone: '+91 886 4414692',
                      company: 'Widgets Ltd'},
  ];

  constructor() { }

  ngOnInit(): void {
  }

}
